spring:
  application:
    name: class-service
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://madaraxghost404:rZd9rwWtNqL7CWVr@classroom.5qglv.mongodb.net/?appName=classroom}
      database: ${MONGODB_DATABASE:classroom}

# Server Configuration
server:
  port: 8082

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:c0349809771c2601589f51e8ee2d970d04b66d5237cc7c5e}

# Connective Meeting Configuration
connective:
  base-url: ${CONNECTIVE_BASE_URL:https://localhost:4000}
  shared-secret: ${CONNECTIVE_SHARED_SECRET:}

logging:
  level:
    com.learnsphere.class_service: DEBUG


